[
    {
        "user": "U7R5CEDAL",
        "type": "message",
        "ts": "1516706532.000076",
        "text": "Morning all - minor update re the recursion issue I was having with vscode last week, confirmed as an issue : <https:\/\/github.com\/Microsoft\/vscode-python\/issues\/581>",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "g426bce8bd0b",
            "image_72": "https:\/\/secure.gravatar.com\/avatar\/3426bce8bd0b04d1d560bace1f1f04af.jpg?s=72&d=https%3A%2F%2Fa.slack-edge.com%2Fdf10d%2Fimg%2Favatars%2Fava_0012-72.png",
            "first_name": "",
            "real_name": "Ian",
            "display_name": "Ian",
            "team": "T4G9NBD2M",
            "name": "ian",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "attachments": [
            {
                "service_name": "GitHub",
                "title": "locals behaviour different between debug and start without debugging 路 Issue #581 路 Microsoft\/vscode-python",
                "title_link": "https:\/\/github.com\/Microsoft\/vscode-python\/issues\/581",
                "text": "Environment data VS Code version: 1.19.2 Python Extension version: 0.9.1 Python Version: 3.6.3 OS and version: Mac OS X 10.13.2 Actual behavior VS Code debug behaviour different than \"start w...",
                "fallback": "GitHub: locals behaviour different between debug and start without debugging 路 Issue #581 路 Microsoft\/vscode-python",
                "from_url": "https:\/\/github.com\/Microsoft\/vscode-python\/issues\/581",
                "thumb_url": "https:\/\/avatars2.githubusercontent.com\/u\/33291557?s=400&v=4",
                "thumb_width": 250,
                "thumb_height": 250,
                "service_icon": "https:\/\/a.slack-edge.com\/bfaba\/img\/unfurl_icons\/github.png",
                "id": 1
            }
        ],
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "y3lK",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "Morning all - minor update re the recursion issue I was having with vscode last week, confirmed as an issue : "
                            },
                            {
                                "type": "link",
                                "url": "https:\/\/github.com\/Microsoft\/vscode-python\/issues\/581"
                            }
                        ]
                    }
                ]
            }
        ],
        "reactions": [
            {
                "name": "+1",
                "users": [
                    "U4H19D1D2"
                ],
                "count": 1
            }
        ]
    }
]