[
    {
        "user": "UDVM2FWGM",
        "type": "message",
        "ts": "1577902404.133900",
        "client_msg_id": "fabb0ac2-a24b-45f1-8163-cf738eb8b64f",
        "text": "Hi guys, no better answer than \"use certs\" on the question \"how to reuse session token when using login interactive?\" ? :smile: Thanks a lot",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "g2d6b5797559",
            "image_72": "https:\/\/secure.gravatar.com\/avatar\/62d6b579755927b3e9e0e2be2b25a452.jpg?s=72&d=https%3A%2F%2Fa.slack-edge.com%2Fdf10d%2Fimg%2Favatars%2Fava_0025-72.png",
            "first_name": "",
            "real_name": "Rob",
            "display_name": "",
            "team": "T4G9NBD2M",
            "name": "robert.ramalhoto",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "ybvhS",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "Hi guys, no better answer than \"use certs\" on the question \"how to reuse session token when using login interactive?\" ? "
                            },
                            {
                                "type": "emoji",
                                "name": "smile",
                                "unicode": "1f604"
                            },
                            {
                                "type": "text",
                                "text": " Thanks a lot"
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        "user": "U4H19D1D2",
        "type": "message",
        "ts": "1577903124.134100",
        "client_msg_id": "B5B5922D-30ED-4D92-804E-D9F2B052EF90",
        "text": "Huh?",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "137c5a3ef323",
            "image_72": "https:\/\/avatars.slack-edge.com\/2024-03-15\/6819395173841_137c5a3ef323f1944a1a_72.png",
            "first_name": "liam",
            "real_name": "liam",
            "display_name": "liam",
            "team": "T4G9NBD2M",
            "name": "liam",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "lq1",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "Huh?"
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        "text": "Hi guys, how can i deal with this error\nI used\nwhile time &lt; future time:\n....try:\n........get updates.\n....except:\n```stream.stop()\ntime.sleep(1)\nstream.start(async_=True)```\nbut i doesn't  help. the code stops. i thought if i put a while loop, then when error occurs it will sleep for 1 second and then start the stream again.but still the code stops.  thanks",
        "files": [
            {
                "id": "FS911GVF0",
                "mode": "hidden_by_limit"
            }
        ],
        "upload": true,
        "user": "US6CDMD7Z",
        "display_as_bot": false,
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "EeXW",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "Hi guys, how can i deal with this error\nI used\nwhile time < future time:\n....try:\n........get updates.\n....except:\n"
                            }
                        ]
                    },
                    {
                        "type": "rich_text_preformatted",
                        "elements": [
                            {
                                "type": "text",
                                "text": "stream.stop()\ntime.sleep(1)\nstream.start(async_=True)"
                            }
                        ]
                    },
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "but i doesn't  help. the code stops. i thought if i put a while loop, then when error occurs it will sleep for 1 second and then start the stream again.but still the code stops.  thanks"
                            }
                        ]
                    }
                ]
            }
        ],
        "type": "message",
        "ts": "1577926747.137000",
        "edited": {
            "user": "US6CDMD7Z",
            "ts": "1577931836.000000"
        },
        "client_msg_id": "148913ef-12c9-4c18-95e4-905fd870727f"
    }
]