[
    {
        "user": "U01PJ5YMFBJ",
        "type": "message",
        "ts": "1727294097.316609",
        "client_msg_id": "0f53070a-c49e-409c-b9ea-8a16ae3a5b77",
        "text": "Hi, I am trying to setup a new AWS Ubuntu 24.04 VM, and have all the python bits and pieces setup, and my certs folder, but am getting the following SSL error. I'm sure i've had this before, but can't remember how I resolved it, any ideas anyone? I'm thinking maybe an OpenSSL problem?\n```HTTPSConnectionPool(host='<http:\/\/identitysso-cert.betfair.com|identitysso-cert.betfair.com>', port=443): Max retries exceeded with url: \/api\/certlogin (Caused by SSLError(SSLError(524297, '[SSL] PEM lib (_ssl.c:3895)'```",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "g819c7f591cc",
            "image_72": "https:\/\/secure.gravatar.com\/avatar\/819c7f591cc888486f19b3f2f49f2011.jpg?s=72&d=https%3A%2F%2Fa.slack-edge.com%2Fdf10d%2Fimg%2Favatars%2Fava_0014-72.png",
            "first_name": "AndyL",
            "real_name": "AndyL",
            "display_name": "AndyL",
            "team": "T4G9NBD2M",
            "name": "andrew_m_leonard",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "thread_ts": "1727294097.316609",
        "reply_count": 4,
        "reply_users_count": 2,
        "latest_reply": "1727333187.769459",
        "reply_users": [
            "U01PJ5YMFBJ",
            "UUE6E1LA1"
        ],
        "replies": [
            {
                "user": "U01PJ5YMFBJ",
                "ts": "1727294654.332859"
            },
            {
                "user": "U01PJ5YMFBJ",
                "ts": "1727295579.022219"
            },
            {
                "user": "UUE6E1LA1",
                "ts": "1727302628.047209"
            },
            {
                "user": "U01PJ5YMFBJ",
                "ts": "1727333187.769459"
            }
        ],
        "is_locked": false,
        "subscribed": false,
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "y58mh",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "Hi, I am trying to setup a new AWS Ubuntu 24.04 VM, and have all the python bits and pieces setup, and my certs folder, but am getting the following SSL error. I'm sure i've had this before, but can't remember how I resolved it, any ideas anyone? I'm thinking maybe an OpenSSL problem?\n"
                            }
                        ]
                    },
                    {
                        "type": "rich_text_preformatted",
                        "elements": [
                            {
                                "type": "text",
                                "text": "HTTPSConnectionPool(host='identitysso-cert.betfair.com', port=443): Max retries exceeded with url: \/api\/certlogin (Caused by SSLError(SSLError(524297, '[SSL] PEM lib (_ssl.c:3895)'"
                            }
                        ],
                        "border": 0
                    }
                ]
            }
        ]
    },
    {
        "user": "U01PJ5YMFBJ",
        "type": "message",
        "ts": "1727294654.332859",
        "client_msg_id": "a55ad0c0-01a2-45a2-83af-13aa081ed63b",
        "text": "probably AWS VM os difference...\nmaybe best to run in docker and avoid all this mess!",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "g819c7f591cc",
            "image_72": "https:\/\/secure.gravatar.com\/avatar\/819c7f591cc888486f19b3f2f49f2011.jpg?s=72&d=https%3A%2F%2Fa.slack-edge.com%2Fdf10d%2Fimg%2Favatars%2Fava_0014-72.png",
            "first_name": "AndyL",
            "real_name": "AndyL",
            "display_name": "AndyL",
            "team": "T4G9NBD2M",
            "name": "andrew_m_leonard",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "thread_ts": "1727294097.316609",
        "parent_user_id": "U01PJ5YMFBJ",
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "DD6oB",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "probably AWS VM os difference...\nmaybe best to run in docker and avoid all this mess!"
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        "user": "U01PJ5YMFBJ",
        "type": "message",
        "ts": "1727295579.022219",
        "client_msg_id": "e95303ee-508e-4682-a0b3-698664610e3e",
        "text": "So yeah, scrapped the Ubunto 24.04 VM, and got a 20.04, and works fine",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "g819c7f591cc",
            "image_72": "https:\/\/secure.gravatar.com\/avatar\/819c7f591cc888486f19b3f2f49f2011.jpg?s=72&d=https%3A%2F%2Fa.slack-edge.com%2Fdf10d%2Fimg%2Favatars%2Fava_0014-72.png",
            "first_name": "AndyL",
            "real_name": "AndyL",
            "display_name": "AndyL",
            "team": "T4G9NBD2M",
            "name": "andrew_m_leonard",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "thread_ts": "1727294097.316609",
        "parent_user_id": "U01PJ5YMFBJ",
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "fYmwh",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "So yeah, scrapped the Ubunto 24.04 VM, and got a 20.04, and works fine"
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        "user": "UUE6E1LA1",
        "type": "message",
        "ts": "1727302628.047209",
        "client_msg_id": "f00114d3-bd04-4631-80f4-ec41b832cd1b",
        "text": "How old are your certs? I remember having to do an openssl hack ages ago because my certs were generated with an older encryption and I had to lower the security setting in the openssl configs (or something like that). I ended up generating newer certs in the end and the problem went away. I think the cause was something to do with a newer version of openssl.\nMight not be related to your issue but thought I'd mention anyway as I've had SSL cert issues on fresh installs before.",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "gf53cae45edd",
            "image_72": "https:\/\/secure.gravatar.com\/avatar\/f53cae45edd7f7b67bbe98819597612e.jpg?s=72&d=https%3A%2F%2Fa.slack-edge.com%2Fdf10d%2Fimg%2Favatars%2Fava_0017-72.png",
            "first_name": "",
            "real_name": "D C",
            "display_name": "D C",
            "team": "T4G9NBD2M",
            "name": "oddsvantage",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "thread_ts": "1727294097.316609",
        "parent_user_id": "U01PJ5YMFBJ",
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "Mx9\/L",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "How old are your certs? I remember having to do an openssl hack ages ago because my certs were generated with an older encryption and I had to lower the security setting in the openssl configs (or something like that). I ended up generating newer certs in the end and the problem went away. I think the cause was something to do with a newer version of openssl.\nMight not be related to your issue but thought I'd mention anyway as I've had SSL cert issues on fresh installs before."
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        "user": "U01PJ5YMFBJ",
        "type": "message",
        "ts": "1727333187.769459",
        "client_msg_id": "A5CDF865-1032-445D-9BC1-7A8E9867107A",
        "text": "Thanks <@UUE6E1LA1> I think it is an openssl issue due to the certs, using v1.1.1 is fine. Iâ€™ll recreate them at some point\nCheers ",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "g819c7f591cc",
            "image_72": "https:\/\/secure.gravatar.com\/avatar\/819c7f591cc888486f19b3f2f49f2011.jpg?s=72&d=https%3A%2F%2Fa.slack-edge.com%2Fdf10d%2Fimg%2Favatars%2Fava_0014-72.png",
            "first_name": "AndyL",
            "real_name": "AndyL",
            "display_name": "AndyL",
            "team": "T4G9NBD2M",
            "name": "andrew_m_leonard",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "thread_ts": "1727294097.316609",
        "parent_user_id": "U01PJ5YMFBJ",
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "eF4eC",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "Thanks "
                            },
                            {
                                "type": "user",
                                "user_id": "UUE6E1LA1"
                            },
                            {
                                "type": "text",
                                "text": " I think it is an openssl issue due to the certs, using v1.1.1 is fine. "
                            },
                            {
                                "type": "text",
                                "text": "Iâ€™ll"
                            },
                            {
                                "type": "text",
                                "text": " recreate them at some point\nCheers "
                            }
                        ]
                    }
                ]
            }
        ]
    }
]