[
    {
        "user": "U027P3N2WMQ",
        "type": "message",
        "ts": "1653942209.991519",
        "client_msg_id": "e399d72b-b23d-4d80-b47b-f9c49d10c2f1",
        "text": "Hi, I'm getting the following error when trying to pull a file list (same code as example) `json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)`\n\nDuring handling of the above exception, another exception occurred:",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "gc41721181dc",
            "image_72": "https:\/\/secure.gravatar.com\/avatar\/c41721181dc4833c08c32f14cddc81b6.jpg?s=72&d=https%3A%2F%2Fa.slack-edge.com%2Fdf10d%2Fimg%2Favatars%2Fava_0026-72.png",
            "first_name": "Michael",
            "real_name": "Michael Leary",
            "display_name": "Michael",
            "team": "T4G9NBD2M",
            "name": "michaelleary15",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "n5My=",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "Hi, I'm getting the following error when trying to pull a file list (same code as example) "
                            },
                            {
                                "type": "text",
                                "text": "json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)",
                                "style": {
                                    "code": true
                                }
                            },
                            {
                                "type": "text",
                                "text": "\n\nDuring handling of the above exception, another exception occurred:"
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        "user": "UFTBRB3F1",
        "type": "message",
        "ts": "1653943814.828029",
        "client_msg_id": "c272c6a4-076b-435d-9eab-fdab8ba6fdcf",
        "text": "Sounds like an invalid json file from that error?",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "g771e110be94",
            "image_72": "https:\/\/secure.gravatar.com\/avatar\/a771e110be945b86bede9d5c1bb551e3.jpg?s=72&d=https%3A%2F%2Fa.slack-edge.com%2Fdf10d%2Fimg%2Favatars%2Fava_0024-72.png",
            "first_name": "",
            "real_name": "Newbie99",
            "display_name": "",
            "team": "T4G9NBD2M",
            "name": "vjmehra",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "thread_ts": "1653943814.828029",
        "reply_count": 1,
        "reply_users_count": 1,
        "latest_reply": "1653948385.321979",
        "reply_users": [
            "U027P3N2WMQ"
        ],
        "replies": [
            {
                "user": "U027P3N2WMQ",
                "ts": "1653948385.321979"
            }
        ],
        "is_locked": false,
        "subscribed": false,
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "xw=2",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "Sounds like an invalid json file from that error?"
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        "user": "U027P3N2WMQ",
        "type": "message",
        "ts": "1653948385.321979",
        "client_msg_id": "45ccdb08-31f9-419f-968a-60019f5e734e",
        "text": "I copied the code directly from the docs so it shouldn't be wrong. All I'm thinking does that mean theres an invalid app key or something similar?",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "gc41721181dc",
            "image_72": "https:\/\/secure.gravatar.com\/avatar\/c41721181dc4833c08c32f14cddc81b6.jpg?s=72&d=https%3A%2F%2Fa.slack-edge.com%2Fdf10d%2Fimg%2Favatars%2Fava_0026-72.png",
            "first_name": "Michael",
            "real_name": "Michael Leary",
            "display_name": "Michael",
            "team": "T4G9NBD2M",
            "name": "michaelleary15",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "thread_ts": "1653943814.828029",
        "parent_user_id": "UFTBRB3F1",
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "xITNn",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "I copied the code directly from the docs so it shouldn't be wrong. All I'm thinking does that mean theres an invalid app key or something similar?"
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        "user": "U02GGCCLTKM",
        "type": "message",
        "ts": "1653948524.171739",
        "client_msg_id": "4c917403-407a-41e9-8c57-796a4e5aafa7",
        "text": "Im guessing probably invalid credentials\/app key causing you to get an error message as a response (rather than a valid json response)",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "ge8c986b4886",
            "image_72": "https:\/\/secure.gravatar.com\/avatar\/e8c986b48866eae41e70e68deddde864.jpg?s=72&d=https%3A%2F%2Fa.slack-edge.com%2Fdf10d%2Fimg%2Favatars%2Fava_0024-72.png",
            "first_name": "John",
            "real_name": "John Foley",
            "display_name": "John Foley",
            "team": "T4G9NBD2M",
            "name": "johnf1004",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "lj2",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "Im guessing probably invalid credentials\/app key causing you to get an error message as a response (rather than a valid json response)"
                            }
                        ]
                    }
                ]
            }
        ]
    }
]