[
    {
        "user": "U01LD279D16",
        "type": "message",
        "ts": "1668596375.494329",
        "client_msg_id": "ce79c3b8-4022-429a-b00c-0dc10e89895d",
        "text": "I have an issue that sometimes appears after a `connection closed by server` error. When the flumine strategy reconnects, it can sometimes get stuck in a cancelling loop. My cancel logic checks whether an order has Executable status, and then cancels based on time executable. Sometimes after a reconnect the strategy attempts to cancel an order, and this transaction fails as `bet_taken_or_lapsed`. The strategy will continually try to cancel these orders, so I'm wondering what the best way to avoid this is.",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "g5488a29f6fb",
            "image_72": "https:\/\/secure.gravatar.com\/avatar\/5488a29f6fbcfe8df23382d16a596068.jpg?s=72&d=https%3A%2F%2Fa.slack-edge.com%2Fdf10d%2Fimg%2Favatars%2Fava_0008-72.png",
            "first_name": "Peter",
            "real_name": "Peter C",
            "display_name": "Peter C",
            "team": "T4G9NBD2M",
            "name": "peter.carter304",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "+74K",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "I have an issue that sometimes appears after a "
                            },
                            {
                                "type": "text",
                                "text": "connection closed by server",
                                "style": {
                                    "code": true
                                }
                            },
                            {
                                "type": "text",
                                "text": " error. When the flumine strategy reconnects, it can sometimes get stuck in a cancelling loop. My cancel logic checks whether an order has Executable status, and then cancels based on time executable. Sometimes after a reconnect the strategy attempts to cancel an order, and this transaction fails as "
                            },
                            {
                                "type": "text",
                                "text": "bet_taken_or_lapsed",
                                "style": {
                                    "code": true
                                }
                            },
                            {
                                "type": "text",
                                "text": ". The strategy will continually try to cancel these orders, so I'm wondering what the best way to avoid this is."
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        "user": "UUCD6P13J",
        "type": "message",
        "ts": "1668596503.183489",
        "client_msg_id": "c5dc3ab7-ca9d-4d2d-bade-31ae030ff911",
        "text": "What version of flumine are you running? I believe this was fixed in 2.2.3",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "g6898272ab81",
            "image_72": "https:\/\/secure.gravatar.com\/avatar\/6898272ab810e419c2c9ca9af1e53da8.jpg?s=72&d=https%3A%2F%2Fa.slack-edge.com%2Fdf10d%2Fimg%2Favatars%2Fava_0012-72.png",
            "first_name": "Lee",
            "real_name": "Lee U",
            "display_name": "Lee",
            "team": "T4G9NBD2M",
            "name": "lunswor",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "PSa4",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "What version of flumine are you running? I believe this was fixed in 2.2.3"
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        "user": "U01LD279D16",
        "type": "message",
        "ts": "1668596837.528219",
        "client_msg_id": "e79a2beb-0a07-4394-9471-50f51a7f9da6",
        "text": "Yep, that's it - I updated flumine everywhere but the server where this problem occurs - sorry, I should have realised, thanks!",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "g5488a29f6fb",
            "image_72": "https:\/\/secure.gravatar.com\/avatar\/5488a29f6fbcfe8df23382d16a596068.jpg?s=72&d=https%3A%2F%2Fa.slack-edge.com%2Fdf10d%2Fimg%2Favatars%2Fava_0008-72.png",
            "first_name": "Peter",
            "real_name": "Peter C",
            "display_name": "Peter C",
            "team": "T4G9NBD2M",
            "name": "peter.carter304",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "hm20",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "Yep, that's it - I updated flumine everywhere but the server where this problem occurs - sorry, I should have realised, thanks!"
                            }
                        ]
                    }
                ]
            }
        ],
        "reactions": [
            {
                "name": "+1",
                "users": [
                    "UUCD6P13J"
                ],
                "count": 1
            }
        ]
    }
]