[
    {
        "user": "U05KECSV68N",
        "type": "message",
        "ts": "1696701072.446129",
        "edited": {
            "user": "U05KECSV68N",
            "ts": "1696701116.000000"
        },
        "client_msg_id": "fdd3f99d-9571-486e-816d-916bd77d34f7",
        "text": "Hi <@U4H19D1D2>. Continuing on the last query I posted on the channel. I'm now using blotter in process_market_book for checking if my orders get traded and it seems to be working well in most of the cases. However, in one of the trades I got execution_complete status immediately, but it took a lot of time for size_remaining & matched_size to update(1 second). Could this exception happen sometimes? Just to note I also submitted a cancellation request for the same order as market moved through my quote in the tick & I didn't see any trade happen on that quote(because size_matched didn't update, so I pushed a cancellation request) & got an Execution_Complete status in the next tick(not sure if this was because of the trade happening in the last tick or my cancellation). So could it be that the cancellation request on a matched order is causing this delay or some sort of error at the exchange?",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "gc2bc41d6054",
            "image_72": "https:\/\/secure.gravatar.com\/avatar\/c2bc41d60540ec3895c1d64cf560d276.jpg?s=72&d=https%3A%2F%2Fa.slack-edge.com%2Fdf10d%2Fimg%2Favatars%2Fava_0017-72.png",
            "first_name": "Rishab",
            "real_name": "Rishab",
            "display_name": "Rishab",
            "team": "T4G9NBD2M",
            "name": "ris499",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "thread_ts": "1696701072.446129",
        "reply_count": 1,
        "reply_users_count": 1,
        "latest_reply": "1696785665.735569",
        "reply_users": [
            "U05KECSV68N"
        ],
        "replies": [
            {
                "user": "U05KECSV68N",
                "ts": "1696785665.735569"
            }
        ],
        "is_locked": false,
        "subscribed": true,
        "last_read": "1696785665.735569",
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "ugsN5",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "Hi "
                            },
                            {
                                "type": "user",
                                "user_id": "U4H19D1D2"
                            },
                            {
                                "type": "text",
                                "text": ". Continuing on the last query I posted on the channel. I'm now using blotter in process_market_book for checking if my orders get traded and it seems to be working well in most of the cases. However, in one of the trades I got execution_complete status immediately, but it took a lot of time for size_remaining & matched_size to update(1 second). Could this exception happen sometimes? Just to note I also submitted a cancellation request for the same order as market moved through my quote in the tick & I didn't see any trade happen on that quote(because size_matched didn't update, so I pushed a cancellation request) & got an Execution_Complete status in the next tick(not sure if this was because of the trade happening in the last tick or my cancellation). So could it be that the cancellation request on a matched order is causing this delay or some sort of error at the exchange?"
                            }
                        ]
                    }
                ]
            }
        ]
    }
]