[
    {
        "user": "U01SNS27HP1",
        "type": "message",
        "ts": "1734037411.087209",
        "client_msg_id": "4008a17e-ab6c-4688-ae56-96c0d73ab6d6",
        "text": "Hi - apologies noob noob trying to reboot attempts at this. I have a fail when trying to install flumine  as output below shows. I will read line by line and try to resolve myself but if anyone can ident my idiocity easily and point me in the right direction, that's great - I'll keep this window open :wink:\n\nUsing cached typing_extensions-4.12.2-py3-none-any.whl (37 kB)\nBuilding wheels for collected packages: pydantic-core\n  Building wheel for pydantic-core (pyproject.toml) ... error\n  error: subprocess-exited-with-error\n\n  × Building wheel for pydantic-core (pyproject.toml) did not run successfully.\n  │ exit code: 1\n  ╰─&gt; [115 lines of output]\n      Running `maturin pep517 build-wheel -i \/Users\/ian\/miniconda3\/envs\/fex\/bin\/python --compatibility off`\n      :package: Including license file \"\/private\/var\/folders\/b6\/6bn7gvx54lv2p4kjxcdz2s0h0000gn\/T\/pip-install-9p34jo51\/pydantic-core_97eb83b395414c3f9cf1c80056b9a571\/LICENSE\"\n      :tropical_drink: Building a mixed python\/rust project\n      :link: Found pyo3 bindings\n      :snake: Found CPython 3.13 at \/Users\/ian\/miniconda3\/envs\/fex\/bin\/python\n      :satellite_antenna: Using build options features, bindings from pyproject.toml\n      :computer: Using `MACOSX_DEPLOYMENT_TARGET=11.0` for aarch64-apple-darwin by default\n         Compiling autocfg v1.1.0\n         Compiling proc-macro2 v1.0.76\n         Compiling unicode-ident v1.0.10\n         Compiling target-lexicon v0.12.9\n         Compiling python3-dll-a v0.2.9\n         Compiling libc v0.2.147\n         Compiling once_cell v1.18.0\n         Compiling version_check v0.9.4\n         Compiling cfg-if v1.0.0\n         Compiling static_assertions v1.1.0\n         Compiling heck v0.4.1\n         Compiling zerocopy v0.7.32\n         Compiling parking_lot_core v0.9.8\n         Compiling rustversion v1.0.13\n         Compiling scopeguard v1.1.0\n         Compiling lexical-util v0.8.5\n         Compiling allocator-api2 v0.2.16\n         Compiling smallvec v1.11.2\n         Compiling tinyvec_macros v0.1.1\n         Compiling serde v1.0.195\n         Compiling tinyvec v1.6.0\n         Compiling memchr v2.6.3\n         Compiling equivalent v1.0.1\n         Compiling unicode-bidi v0.3.13\n         Compiling regex-syntax v0.8.2\n         Compiling ahash v0.8.7\n         Compiling num-traits v0.2.16\n         Compiling num-integer v0.1.45\n         Compiling lock_api v0.4.10\n         Compiling memoffset v0.9.0\n         Compiling num-bigint v0.4.4\n         Compiling lexical-write-integer v0.8.5\n         Compiling lexical-parse-integer v0.8.6\n         Compiling unicode-normalization v0.1.22\n         Compiling lexical-write-float v0.8.5\n         Compiling lexical-parse-float v0.8.5\n         Compiling aho-corasick v1.0.2\n         Compiling indoc v2.0.4\n         Compiling serde_json v1.0.109\n         Compiling percent-encoding v2.3.1\n         Compiling unindent v0.2.3\n         Compiling form_urlencoded v1.2.1\n         Compiling regex-automata v0.4.3\n         Compiling lexical-core v0.8.5\n         Compiling idna v0.5.0\n         Compiling ryu v1.0.14\n         Compiling itoa v1.0.8\n         Compiling uuid v1.6.1\n         Compiling base64 v0.21.7\n         Compiling url v2.5.0\n         Compiling regex v1.10.2\n         Compiling quote v1.0.35\n         Compiling syn v2.0.48\n         Compiling pyo3-build-config v0.20.2\n         Compiling getrandom v0.2.10\n         Compiling parking_lot v0.12.1\n         Compiling hashbrown v0.14.3\n         Compiling pyo3-ffi v0.20.2\n         Compiling pyo3 v0.20.2\n         Compiling pydantic-core v2.16.3 (\/private\/var\/folders\/b6\/6bn7gvx54lv2p4kjxcdz2s0h0000gn\/T\/pip-install-9p34jo51\/pydantic-core_97eb83b395414c3f9cf1c80056b9a571)\n         Compiling indexmap v2.0.0\n      error: failed to run custom build command for `pydantic-core v2.16.3 (\/private\/var\/folders\/b6\/6bn7gvx54lv2p4kjxcdz2s0h0000gn\/T\/pip-install-9p34jo51\/pydantic-core_97eb83b395414c3f9cf1c80056b9a571)`\n\n      Caused by:\n        process didn't exit successfully: `\/private\/var\/folders\/b6\/6bn7gvx54lv2p4kjxcdz2s0h0000gn\/T\/pip-install-9p34jo51\/pydantic-core_97eb83b395414c3f9cf1c80056b9a571\/target\/release\/build\/pydantic-core-39a2e9245b501e5a\/build-script-build` (exit status: 101)\n        --- stdout\n        cargo:rustc-cfg=Py_3_6\n        cargo:rustc-cfg=Py_3_7\n        cargo:rustc-cfg=Py_3_8\n        cargo:rustc-cfg=Py_3_9\n        cargo:rustc-cfg=Py_3_10\n        cargo:rustc-cfg=Py_3_11\n        cargo:rustc-cfg=Py_3_12\n        cargo:rustc-cfg=Py_3_13\n        cargo:rerun-if-changed=python\/pydantic_core\/core_schema.py\n        cargo:rerun-if-changed=generate_self_schema.py\n\n        --- stderr\n        Traceback (most recent call last):\n          File \"\/private\/var\/folders\/b6\/6bn7gvx54lv2p4kjxcdz2s0h0000gn\/T\/pip-install-9p34jo51\/pydantic-core_97eb83b395414c3f9cf1c80056b9a571\/generate_self_schema.py\", line 192, in eval_forward_ref\n            return type_._evaluate(core_schema.__dict__, None, set())\n                   ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'\n\n        During handling of the above exception, another exception occurred:\n\n        Traceback (most recent call last):\n          File \"\/private\/var\/folders\/b6\/6bn7gvx54lv2p4kjxcdz2s0h0000gn\/T\/pip-install-9p34jo51\/pydantic-core_97eb83b395414c3f9cf1c80056b9a571\/generate_self_schema.py\", line 240, in &lt;module&gt;\n            main()\n            ~~~~^^\n          File \"\/private\/var\/folders\/b6\/6bn7gvx54lv2p4kjxcdz2s0h0000gn\/T\/pip-install-9p34jo51\/pydantic-core_97eb83b395414c3f9cf1c80056b9a571\/generate_self_schema.py\", line 210, in main\n            value = get_schema(s, definitions)\n          File \"\/private\/var\/folders\/b6\/6bn7gvx54lv2p4kjxcdz2s0h0000gn\/T\/pip-install-9p34jo51\/pydantic-core_97eb83b395414c3f9cf1c80056b9a571\/generate_self_schema.py\", line 54, in get_schema\n            return type_dict_schema(obj, definitions)\n          File \"\/private\/var\/folders\/b6\/6bn7gvx54lv2p4kjxcdz2s0h0000gn\/T\/pip-install-9p34jo51\/pydantic-core_97eb83b395414c3f9cf1c80056b9a571\/generate_self_schema.py\", line 152, in type_dict_schema\n            field_type = eval_forward_ref(field_type)\n          File \"\/private\/var\/folders\/b6\/6bn7gvx54lv2p4kjxcdz2s0h0000gn\/T\/pip-install-9p34jo51\/pydantic-core_97eb83b395414c3f9cf1c80056b9a571\/generate_self_schema.py\", line 195, in eval_forward_ref\n            return type_._evaluate(core_schema.__dict__, None)\n                   ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'\n        thread 'main' panicked at <http:\/\/build.rs:29:9|build.rs:29:9>:\n        generate_self_schema.py failed with exit status: 1\n        note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n      warning: build failed, waiting for other jobs to finish...\n      :boom: maturin failed\n        Caused by: Failed to build a native library through cargo\n        Caused by: Cargo build finished with \"exit status: 101\": `env -u CARGO MACOSX_DEPLOYMENT_TARGET=\"11.0\" PYO3_ENVIRONMENT_SIGNATURE=\"cpython-3.13-64bit\" PYO3_PYTHON=\"\/Users\/ian\/miniconda3\/envs\/fex\/bin\/python\" PYTHON_SYS_EXECUTABLE=\"\/Users\/ian\/miniconda3\/envs\/fex\/bin\/python\" \"cargo\" \"rustc\" \"--features\" \"pyo3\/extension-module\" \"--message-format\" \"json-render-diagnostics\" \"--manifest-path\" \"\/private\/var\/folders\/b6\/6bn7gvx54lv2p4kjxcdz2s0h0000gn\/T\/pip-install-9p34jo51\/pydantic-core_97eb83b395414c3f9cf1c80056b9a571\/Cargo.toml\" \"--release\" \"--lib\" \"--crate-type\" \"cdylib\" \"--\" \"-C\" \"link-arg=-undefined\" \"-C\" \"link-arg=dynamic_lookup\" \"-C\" \"link-args=-Wl,-install_name,@rpath\/pydantic_core._pydantic_core.cpython-313-darwin.so\"`\n      Error: command ['maturin', 'pep517', 'build-wheel', '-i', '\/Users\/ian\/miniconda3\/envs\/fex\/bin\/python', '--compatibility', 'off'] returned non-zero exit status 1\n      [end of output]\n\n  note: This error originates from a subprocess, and is likely not a problem with pip.\n  ERROR: Failed building wheel for pydantic-core\nFailed to build pydantic-core\nERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pydantic-core)",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "g904ba89dcab",
            "image_72": "https:\/\/secure.gravatar.com\/avatar\/904ba89dcab76403af1e656f31132e78.jpg?s=72&d=https%3A%2F%2Fa.slack-edge.com%2Fdf10d%2Fimg%2Favatars%2Fava_0012-72.png",
            "first_name": "",
            "real_name": "ian mcneill",
            "display_name": "ian mcneill",
            "team": "T4G9NBD2M",
            "name": "ian.mcneill",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "Bv4ep",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "Hi - apologies noob noob trying to reboot attempts at this. I have a fail when trying to install flumine  as output below shows. I will read line by line and try to resolve myself but if anyone can ident my idiocity easily and point me in the right direction, that's great - I'll keep this window open "
                            },
                            {
                                "type": "emoji",
                                "name": "wink",
                                "unicode": "1f609"
                            },
                            {
                                "type": "text",
                                "text": "\n\nUsing cached typing_extensions-4.12.2-py3-none-any.whl (37 kB)\nBuilding wheels for collected packages: pydantic-core\n  Building wheel for pydantic-core (pyproject.toml) ... error\n  error: subprocess-exited-with-error\n\n  × Building wheel for pydantic-core (pyproject.toml) did not run successfully.\n  │ exit code: 1\n  ╰─> [115 lines of output]\n      Running `maturin pep517 build-wheel -i \/Users\/ian\/miniconda3\/envs\/fex\/bin\/python --compatibility off`\n      "
                            },
                            {
                                "type": "emoji",
                                "name": "package",
                                "unicode": "1f4e6"
                            },
                            {
                                "type": "text",
                                "text": " Including license file \"\/private\/var\/folders\/b6\/6bn7gvx54lv2p4kjxcdz2s0h0000gn\/T\/pip-install-9p34jo51\/pydantic-core_97eb83b395414c3f9cf1c80056b9a571\/LICENSE\"\n      "
                            },
                            {
                                "type": "emoji",
                                "name": "tropical_drink",
                                "unicode": "1f379"
                            },
                            {
                                "type": "text",
                                "text": " Building a mixed python\/rust project\n      "
                            },
                            {
                                "type": "emoji",
                                "name": "link",
                                "unicode": "1f517"
                            },
                            {
                                "type": "text",
                                "text": " Found pyo3 bindings\n      "
                            },
                            {
                                "type": "emoji",
                                "name": "snake",
                                "unicode": "1f40d"
                            },
                            {
                                "type": "text",
                                "text": " Found CPython 3.13 at \/Users\/ian\/miniconda3\/envs\/fex\/bin\/python\n      "
                            },
                            {
                                "type": "emoji",
                                "name": "satellite_antenna",
                                "unicode": "1f4e1"
                            },
                            {
                                "type": "text",
                                "text": " Using build options features, bindings from pyproject.toml\n      "
                            },
                            {
                                "type": "emoji",
                                "name": "computer",
                                "unicode": "1f4bb"
                            },
                            {
                                "type": "text",
                                "text": " Using `MACOSX_DEPLOYMENT_TARGET=11.0` for aarch64-apple-darwin by default\n         Compiling autocfg v1.1.0\n         Compiling proc-macro2 v1.0.76\n         Compiling unicode-ident v1.0.10\n         Compiling target-lexicon v0.12.9\n         Compiling python3-dll-a v0.2.9\n         Compiling libc v0.2.147\n         Compiling once_cell v1.18.0\n         Compiling version_check v0.9.4\n         Compiling cfg-if v1.0.0\n         Compiling static_assertions v1.1.0\n         Compiling heck v0.4.1\n         Compiling zerocopy v0.7.32\n         Compiling parking_lot_core v0.9.8\n         Compiling rustversion v1.0.13\n         Compiling scopeguard v1.1.0\n         Compiling lexical-util v0.8.5\n         Compiling allocator-api2 v0.2.16\n         Compiling smallvec v1.11.2\n         Compiling tinyvec_macros v0.1.1\n         Compiling serde v1.0.195\n         Compiling tinyvec v1.6.0\n         Compiling memchr v2.6.3\n         Compiling equivalent v1.0.1\n         Compiling unicode-bidi v0.3.13\n         Compiling regex-syntax v0.8.2\n         Compiling ahash v0.8.7\n         Compiling num-traits v0.2.16\n         Compiling num-integer v0.1.45\n         Compiling lock_api v0.4.10\n         Compiling memoffset v0.9.0\n         Compiling num-bigint v0.4.4\n         Compiling lexical-write-integer v0.8.5\n         Compiling lexical-parse-integer v0.8.6\n         Compiling unicode-normalization v0.1.22\n         Compiling lexical-write-float v0.8.5\n         Compiling lexical-parse-float v0.8.5\n         Compiling aho-corasick v1.0.2\n         Compiling indoc v2.0.4\n         Compiling serde_json v1.0.109\n         Compiling percent-encoding v2.3.1\n         Compiling unindent v0.2.3\n         Compiling form_urlencoded v1.2.1\n         Compiling regex-automata v0.4.3\n         Compiling lexical-core v0.8.5\n         Compiling idna v0.5.0\n         Compiling ryu v1.0.14\n         Compiling itoa v1.0.8\n         Compiling uuid v1.6.1\n         Compiling base64 v0.21.7\n         Compiling url v2.5.0\n         Compiling regex v1.10.2\n         Compiling quote v1.0.35\n         Compiling syn v2.0.48\n         Compiling pyo3-build-config v0.20.2\n         Compiling getrandom v0.2.10\n         Compiling parking_lot v0.12.1\n         Compiling hashbrown v0.14.3\n         Compiling pyo3-ffi v0.20.2\n         Compiling pyo3 v0.20.2\n         Compiling pydantic-core v2.16.3 (\/private\/var\/folders\/b6\/6bn7gvx54lv2p4kjxcdz2s0h0000gn\/T\/pip-install-9p34jo51\/pydantic-core_97eb83b395414c3f9cf1c80056b9a571)\n         Compiling indexmap v2.0.0\n      error: failed to run custom build command for `pydantic-core v2.16.3 (\/private\/var\/folders\/b6\/6bn7gvx54lv2p4kjxcdz2s0h0000gn\/T\/pip-install-9p34jo51\/pydantic-core_97eb83b395414c3f9cf1c80056b9a571)`\n\n      Caused by:\n        process didn't exit successfully: `\/private\/var\/folders\/b6\/6bn7gvx54lv2p4kjxcdz2s0h0000gn\/T\/pip-install-9p34jo51\/pydantic-core_97eb83b395414c3f9cf1c80056b9a571\/target\/release\/build\/pydantic-core-39a2e9245b501e5a\/build-script-build` (exit status: 101)\n        --- stdout\n        cargo:rustc-cfg=Py_3_6\n        cargo:rustc-cfg=Py_3_7\n        cargo:rustc-cfg=Py_3_8\n        cargo:rustc-cfg=Py_3_9\n        cargo:rustc-cfg=Py_3_10\n        cargo:rustc-cfg=Py_3_11\n        cargo:rustc-cfg=Py_3_12\n        cargo:rustc-cfg=Py_3_13\n        cargo:rerun-if-changed=python\/pydantic_core\/core_schema.py\n        cargo:rerun-if-changed=generate_self_schema.py\n\n        --- stderr\n        Traceback (most recent call last):\n          File \"\/private\/var\/folders\/b6\/6bn7gvx54lv2p4kjxcdz2s0h0000gn\/T\/pip-install-9p34jo51\/pydantic-core_97eb83b395414c3f9cf1c80056b9a571\/generate_self_schema.py\", line 192, in eval_forward_ref\n            return type_._evaluate(core_schema.__dict__, None, set())\n                   ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'\n\n        During handling of the above exception, another exception occurred:\n\n        Traceback (most recent call last):\n          File \"\/private\/var\/folders\/b6\/6bn7gvx54lv2p4kjxcdz2s0h0000gn\/T\/pip-install-9p34jo51\/pydantic-core_97eb83b395414c3f9cf1c80056b9a571\/generate_self_schema.py\", line 240, in <module>\n            main()\n            ~~~~^^\n          File \"\/private\/var\/folders\/b6\/6bn7gvx54lv2p4kjxcdz2s0h0000gn\/T\/pip-install-9p34jo51\/pydantic-core_97eb83b395414c3f9cf1c80056b9a571\/generate_self_schema.py\", line 210, in main\n            value = get_schema(s, definitions)\n          File \"\/private\/var\/folders\/b6\/6bn7gvx54lv2p4kjxcdz2s0h0000gn\/T\/pip-install-9p34jo51\/pydantic-core_97eb83b395414c3f9cf1c80056b9a571\/generate_self_schema.py\", line 54, in get_schema\n            return type_dict_schema(obj, definitions)\n          File \"\/private\/var\/folders\/b6\/6bn7gvx54lv2p4kjxcdz2s0h0000gn\/T\/pip-install-9p34jo51\/pydantic-core_97eb83b395414c3f9cf1c80056b9a571\/generate_self_schema.py\", line 152, in type_dict_schema\n            field_type = eval_forward_ref(field_type)\n          File \"\/private\/var\/folders\/b6\/6bn7gvx54lv2p4kjxcdz2s0h0000gn\/T\/pip-install-9p34jo51\/pydantic-core_97eb83b395414c3f9cf1c80056b9a571\/generate_self_schema.py\", line 195, in eval_forward_ref\n            return type_._evaluate(core_schema.__dict__, None)\n                   ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'\n        thread 'main' panicked at build.rs:29:9:\n        generate_self_schema.py failed with exit status: 1\n        note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n      warning: build failed, waiting for other jobs to finish...\n      "
                            },
                            {
                                "type": "emoji",
                                "name": "boom",
                                "unicode": "1f4a5"
                            },
                            {
                                "type": "text",
                                "text": " maturin failed\n        Caused by: Failed to build a native library through cargo\n        Caused by: Cargo build finished with \"exit status: 101\": `env -u CARGO MACOSX_DEPLOYMENT_TARGET=\"11.0\" PYO3_ENVIRONMENT_SIGNATURE=\"cpython-3.13-64bit\" PYO3_PYTHON=\"\/Users\/ian\/miniconda3\/envs\/fex\/bin\/python\" PYTHON_SYS_EXECUTABLE=\"\/Users\/ian\/miniconda3\/envs\/fex\/bin\/python\" \"cargo\" \"rustc\" \"--features\" \"pyo3\/extension-module\" \"--message-format\" \"json-render-diagnostics\" \"--manifest-path\" \"\/private\/var\/folders\/b6\/6bn7gvx54lv2p4kjxcdz2s0h0000gn\/T\/pip-install-9p34jo51\/pydantic-core_97eb83b395414c3f9cf1c80056b9a571\/Cargo.toml\" \"--release\" \"--lib\" \"--crate-type\" \"cdylib\" \"--\" \"-C\" \"link-arg=-undefined\" \"-C\" \"link-arg=dynamic_lookup\" \"-C\" \"link-args=-Wl,-install_name,@rpath\/pydantic_core._pydantic_core.cpython-313-darwin.so\"`\n      Error: command ['maturin', 'pep517', 'build-wheel', '-i', '\/Users\/ian\/miniconda3\/envs\/fex\/bin\/python', '--compatibility', 'off'] returned non-zero exit status 1\n      [end of output]\n\n  note: This error originates from a subprocess, and is likely not a problem with pip.\n  ERROR: Failed building wheel for pydantic-core\nFailed to build pydantic-core\nERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pydantic-core)"
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        "user": "U4H19D1D2",
        "type": "message",
        "ts": "1734037614.657589",
        "client_msg_id": "3A5FB158-33FD-4A9B-A7EB-962309C02896",
        "text": "Python 3.13 is not supported, was this not discussed last time?",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "137c5a3ef323",
            "image_72": "https:\/\/avatars.slack-edge.com\/2024-03-15\/6819395173841_137c5a3ef323f1944a1a_72.png",
            "first_name": "liam",
            "real_name": "liam",
            "display_name": "liam",
            "team": "T4G9NBD2M",
            "name": "liam",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "1QHpw",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "Python 3.13 is not supported, was this not discussed last time?"
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        "user": "U01SNS27HP1",
        "type": "message",
        "ts": "1734037822.296049",
        "client_msg_id": "85a5f91c-5c25-48e3-8693-1b0a198a368e",
        "text": "Apologies - docs say 3.8+",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "g904ba89dcab",
            "image_72": "https:\/\/secure.gravatar.com\/avatar\/904ba89dcab76403af1e656f31132e78.jpg?s=72&d=https%3A%2F%2Fa.slack-edge.com%2Fdf10d%2Fimg%2Favatars%2Fava_0012-72.png",
            "first_name": "",
            "real_name": "ian mcneill",
            "display_name": "ian mcneill",
            "team": "T4G9NBD2M",
            "name": "ian.mcneill",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "v56A0",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "Apologies - docs say 3.8+"
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        "user": "U4H19D1D2",
        "type": "message",
        "ts": "1734038027.227709",
        "client_msg_id": "7B2AEB25-221F-4EB8-9212-C7953184B482",
        "text": "Damn yeah the toml files need updating ",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "137c5a3ef323",
            "image_72": "https:\/\/avatars.slack-edge.com\/2024-03-15\/6819395173841_137c5a3ef323f1944a1a_72.png",
            "first_name": "liam",
            "real_name": "liam",
            "display_name": "liam",
            "team": "T4G9NBD2M",
            "name": "liam",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "9SXYp",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "Damn yeah the "
                            },
                            {
                                "type": "text",
                                "text": "toml files need updating "
                            }
                        ]
                    }
                ]
            }
        ]
    }
]