[
    {
        "user": "U07U8NJF16Z",
        "type": "message",
        "ts": "1735465334.121419",
        "edited": {
            "user": "U07U8NJF16Z",
            "ts": "1735465437.000000"
        },
        "client_msg_id": "ee5b9a1e-b5fb-4c31-8c7f-d66f9ec2e3d5",
        "text": "Hi I've started getting the following error complaining about an invalid session seems intermittent and program still runs and places bets.... should I be worried?:\n\n File \"D:\\Users\\willi\\anaconda3\\Lib\\site-packages\\flumine\\worker.py\", line 126, in poll_market_catalogue\n    market_catalogues = client.betting_client.betting.list_market_catalogue(\n                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Users\\willi\\anaconda3\\Lib\\site-packages\\betfairlightweight\\endpoints\\betting.py\", line 233, in list_market_catalogue\n    (response, response_json, elapsed_time) = self.request(method, params, session)\n                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Users\\willi\\anaconda3\\Lib\\site-packages\\betfairlightweight\\endpoints\\baseendpoint.py\", line 54, in request\n    self._error_handler(response_json, method, params)\n  File \"D:\\Users\\willi\\anaconda3\\Lib\\site-packages\\betfairlightweight\\endpoints\\baseendpoint.py\", line 80, in _error_handler\n    raise self._error(response, method, params)\nbetfairlightweight.exceptions.APIError: SportsAPING\/v1.0\/listMarketCatalogue\nParams: {'filter': {'marketIds': ['1.237584679', '1.237584668', '1.237584666', '1.237584713', '1.237582001', '1.237584706', '1.237584674', '1.237582040', '1.237584707', '1.237584715', '1.237584714', '1.237582041', '1.237584699', '1.237611936', '1.237611941', '1.237611968', '1.237611961', '1.237611945', '1.237611955']}, 'marketProjection': ['COMPETITION', 'EVENT', 'EVENT_TYPE', 'RUNNER_DESCRIPTION', 'RUNNER_METADATA', 'MARKET_START_TIME', 'MARKET_DESCRIPTION'], 'maxResults': 25}\nException: None\nError: {'code': -32099, 'message': 'ANGX-0003', 'data': {'APINGException': {'requestUUID': 'ie2-ang06a-prd-11260945-00381f34ac', 'errorCode': 'INVALID_SESSION_INFORMATION', 'errorDetails': ''}, 'exceptionname': 'APINGException'}}\nFull Response: {'jsonrpc': '2.0', 'error': {'code': -32099, 'message': 'ANGX-0003', 'data': {'APINGException': {'requestUUID': 'ie2-ang06a-prd-11260945-00381f34ac', 'errorCode': 'INVALID_SESSION_INFORMATION', 'errorDetails': ''}, 'exceptionname': 'APINGException'}}, 'id': 1}\n2024-12-29 09:41:16,405:INFO:162:Client update account details\n2024-12-29 09:41:18,027:INFO:263:Updated marketCatalogue for 1.237613210",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "a00c9f162b06",
            "image_72": "https:\/\/avatars.slack-edge.com\/2024-10-31\/7963621300706_a00c9f162b066839969e_72.png",
            "first_name": "William",
            "real_name": "William Rathbone",
            "display_name": "WilliamR",
            "team": "T4G9NBD2M",
            "name": "wrathbon",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "thread_ts": "1735465334.121419",
        "reply_count": 3,
        "reply_users_count": 2,
        "latest_reply": "1735556110.751169",
        "reply_users": [
            "U012XF5CNPN",
            "U07U8NJF16Z"
        ],
        "replies": [
            {
                "user": "U012XF5CNPN",
                "ts": "1735555066.723889"
            },
            {
                "user": "U012XF5CNPN",
                "ts": "1735555112.435329"
            },
            {
                "user": "U07U8NJF16Z",
                "ts": "1735556110.751169"
            }
        ],
        "is_locked": false,
        "subscribed": false,
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "WmjKY",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "Hi I've started getting the following error complaining about an invalid session seems intermittent and program still runs and places bets.... should I be worried?:\n\n File \"D:\\Users\\willi\\anaconda3\\Lib\\site-packages\\flumine\\worker.py\", line 126, in poll_market_catalogue\n    market_catalogues = client.betting_client.betting.list_market_catalogue(\n                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Users\\willi\\anaconda3\\Lib\\site-packages\\betfairlightweight\\endpoints\\betting.py\", line 233, in list_market_catalogue\n    (response, response_json, elapsed_time) = self.request(method, params, session)\n                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Users\\willi\\anaconda3\\Lib\\site-packages\\betfairlightweight\\endpoints\\baseendpoint.py\", line 54, in request\n    self._error_handler(response_json, method, params)\n  File \"D:\\Users\\willi\\anaconda3\\Lib\\site-packages\\betfairlightweight\\endpoints\\baseendpoint.py\", line 80, in _error_handler\n    raise self._error(response, method, params)\nbetfairlightweight.exceptions.APIError: SportsAPING\/v1.0\/listMarketCatalogue\nParams: {'filter': {'marketIds': ['1.237584679', '1.237584668', '1.237584666', '1.237584713', '1.237582001', '1.237584706', '1.237584674', '1.237582040', '1.237584707', '1.237584715', '1.237584714', '1.237582041', '1.237584699', '1.237611936', '1.237611941', '1.237611968', '1.237611961', '1.237611945', '1.237611955']}, 'marketProjection': ['COMPETITION', 'EVENT', 'EVENT_TYPE', 'RUNNER_DESCRIPTION', 'RUNNER_METADATA', 'MARKET_START_TIME', 'MARKET_DESCRIPTION'], 'maxResults': 25}\nException: None\nError: {'code': -32099, 'message': 'ANGX-0003', 'data': {'APINGException': {'requestUUID': 'ie2-ang06a-prd-11260945-00381f34ac', 'errorCode': 'INVALID_SESSION_INFORMATION', 'errorDetails': ''}, 'exceptionname': 'APINGException'}}\nFull Response: {'jsonrpc': '2.0', 'error': {'code': -32099, 'message': 'ANGX-0003', 'data': {'APINGException': {'requestUUID': 'ie2-ang06a-prd-11260945-00381f34ac', 'errorCode': 'INVALID_SESSION_INFORMATION', 'errorDetails': ''}, 'exceptionname': 'APINGException'}}, 'id': 1}\n2024-12-29 09:41:16,405:INFO:162:Client update account details\n2024-12-29 09:41:18,027:INFO:263:Updated marketCatalogue for 1.237613210"
                            }
                        ]
                    }
                ]
            }
        ]
    }
]