[
    {
        "user": "U02TG3K70KW",
        "type": "message",
        "ts": "1713883727.112809",
        "client_msg_id": "a645ce12-d0a8-4442-aca1-f071f0f484f7",
        "text": "Hello everyone,\nfor a couple of days I've been encountering issues during API login.\nbetfairlightweight.exceptions.APIError: None\nParams: None\nException: HTTPSConnectionPool(host='<http:\/\/identitysso-cert.betfair.it|identitysso-cert.betfair.it>', port=443): Max retries exceeded with url: \/api\/certlogin (Caused by ConnectTimeoutError(&lt;urllib3.connection.HTTPSConnection object at 0x71de1340&gt;, 'Connection to <http:\/\/identitysso-cert.betfair.it|identitysso-cert.betfair.it> timed out. (connect timeout=3.05)'))\nThis has never happened to me before, but these days I'm getting this message almost 80% of the time. What can I check to resolve it?",
        "team": "T4G9NBD2M",
        "user_team": "T4G9NBD2M",
        "source_team": "T4G9NBD2M",
        "user_profile": {
            "avatar_hash": "2642325545e6",
            "image_72": "https:\/\/avatars.slack-edge.com\/2022-01-10\/2931861446915_2642325545e6697d2fa4_72.png",
            "first_name": "Dario",
            "real_name": "Dario Scardina",
            "display_name": "Dario Scardina",
            "team": "T4G9NBD2M",
            "name": "dario.scardina",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
        "blocks": [
            {
                "type": "rich_text",
                "block_id": "9J8Lp",
                "elements": [
                    {
                        "type": "rich_text_section",
                        "elements": [
                            {
                                "type": "text",
                                "text": "Hello everyone,\nfor a couple of days I've been encountering issues during API login.\nbetfairlightweight.exceptions.APIError: None\nParams: None\nException: HTTPSConnectionPool(host='"
                            },
                            {
                                "type": "link",
                                "url": "http:\/\/identitysso-cert.betfair.it",
                                "text": "identitysso-cert.betfair.it"
                            },
                            {
                                "type": "text",
                                "text": "', port=443): Max retries exceeded with url: \/api\/certlogin (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x71de1340>, 'Connection to "
                            },
                            {
                                "type": "link",
                                "url": "http:\/\/identitysso-cert.betfair.it",
                                "text": "identitysso-cert.betfair.it"
                            },
                            {
                                "type": "text",
                                "text": " timed out. (connect timeout=3.05)'))\nThis has never happened to me before, but these days I'm getting this message almost 80% of the time. What can I check to resolve it?"
                            }
                        ]
                    }
                ]
            }
        ]
    }
]